### ISSUE TITLE
Remove error warning in the counter

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#11]
![Screenshot from 2020-10-01 21-51-47](https://user-images.githubusercontent.com/54894783/94836499-ad750200-0430-11eb-9be2-6e8722e3c2e5.png)

**Comment by Dheeraj-01** [comment]
Hi, can you assign me to this? Thanks :) 😊

**Comment by hey-ritikgupta** [comment]
Hey I have fixed the error.
