### ISSUE TITLE
Fill readme with valid details.

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#14]
well currently this project has readme but it would be great to have read me with valid details

**Comment by nexuspy** [comment]
Hi @tewarig I'm intrested in these project .. would you like to assign it to me?

**Comment by tewarig** [comment]
sure.. please fill readme with valid details

**Comment by priyankaagrawal123** [comment]
I am interested. I can implement.
Please assign this issue to me.

**Comment by tewarig** [comment]
Done
