### ISSUE TITLE
Add notes for 1 Sem  

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#19]

**Comment by Coolchirutha** [comment]
Tell me which subjects to add. I have a lot of data from my campus which I can add. Can you assign me to this?

**Comment by tewarig** [comment]
done

**Comment by MilindGupta-Creator** [comment]
can you share what coding topics or what subjects material u needed

**Comment by tewarig** [comment]
well each and every topic is important... you can contribute notes on any topic.
