### ISSUE TITLE
Add a new awesome readme

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#2]
please add an awesome new readme for this project

**Comment by Riya-code** [comment]
can I take it?

**Comment by VARhimank** [comment]
can i work on that ? I can make it cool 🆒

**Comment by tewarig** [comment]
yes sure.. go for it.. make a pr. I will accept it.

**Comment by VARhimank** [comment]
Is my pull visible ?
i forked it and committed changes

**Comment by mmuhamadamirzaidi** [comment]
Done @tewarig

**Comment by tewarig** [comment]
well, I have merged the pull requests..thanks, everyone. the issue will remain open.. so that others can also contribute.

**Comment by mmuhamadamirzaidi** [comment]
Thanks @tewarig
