### ISSUE TITLE
Make readme more awesome

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#26]

**Comment by Leviter** [comment]
What do you mean by making it more awesome?
What should be changed?

**Comment by tewarig** [comment]
is there is any way we can add the contributor's name and photos to read me...

**Comment by Leviter** [comment]
I will look into it.... can you assign the issue to me?

**Comment by Leviter** [comment]
I was able to make a quick improvement by adding the photos (dynamically). The names are not supported there.

**Comment by tewarig** [comment]
I think that is fine..thanks
