### ISSUE TITLE
Incorrect Name of the Subject

### ISSUE THREAD

**Issue by azim2429** [tewarig/section-f#29]
![image](https://user-images.githubusercontent.com/60839140/94916203-ddbdae80-04cb-11eb-8d3e-6718c7c1d71a.png)

The name of the subject should be "Logic Design" instead of "Login Design".

**Comment by tewarig** [comment]
well, you can try to fix that ..typo

**Comment by azim2429** [comment]
Okay Sure!

**Comment by fadildillah** [comment]
is it still open? i want to fix this
