### ISSUE TITLE
Add a counter to count number of visitors in the site in the navbar

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#3]

**Comment by manisacharya** [comment]
@tewarig I can give it a try

**Comment by tewarig** [comment]
sure..

**Comment by manisacharya** [comment]
@tewarig Where do you want the visitor site to be placed? I have added at top right section for now.
![image](https://user-images.githubusercontent.com/22543019/94835237-2a07e080-0431-11eb-9b14-212f049c5bb1.png)

**Comment by tewarig** [comment]
well that is a nice place.. please continue.. and make a pr

**Comment by manisacharya** [comment]
@tewarig Check this out https://github.com/tewarig/section-f/pull/15

**Comment by manisacharya** [comment]
Also, you can assign this to me? @tewarig

**Comment by tewarig** [comment]
done.. it is not showing the value of counter...

**Comment by manisacharya** [comment]
I am trying other way around, I was the preview and the js is blocked.

**Comment by manisacharya** [comment]
@tewarig You can see new implementation in the [preview](https://section-f-git-fork-manisacharya-visitor-counter.tewarig.vercel.app/), I have pushed new change.

**Comment by tewarig** [comment]
wow... it looks great.

**Comment by manisacharya** [comment]
Yes @tewarig. We can close this issue now?

**Comment by tewarig** [comment]
yes suree thanks
