### ISSUE TITLE
Web page display changes

### ISSUE THREAD

**Issue by kalpanaT-05** [tewarig/section-f#39]
There's some issues we can fix in responsiveness and some good display as well, so if you can then assign me this issue i can fix it and will make some changes in your web page the view of the web page and alignment

**Comment by tewarig** [comment]
well the site is not responsive now.. please have a look in that also.

**Comment by tewarig** [comment]
https://section-f-git-4ada838599ae4f6c12560e41f7c4fcfb201653b3.tewarig.vercel.app

**Comment by kalpanaT-05** [comment]
sure i'll make changes in that and let you know, will this PR be counted if i make changes?

**Comment by kalpanaT-05** [comment]
hey i have made changes and wants to merge the PR can you check it once again and let it get access towards my hacktoberfest PR
thank you :)
