### ISSUE TITLE
Contribute your notes

### ISSUE THREAD

**Issue by tewarig** [tewarig/section-f#7]
well, this repo helps.. engineering students to study in exams.. so you can contribute your notes you used during college.

**Comment by pooja-gera** [comment]
Hi, can I work on this? I make amazing notes, I'll be done with the third semester notes by 7th October. My handwriting is also Pretty legible and I write content that actually is helpful.

**Comment by tewarig** [comment]
Sure.. thanks

**Comment by Riya-code** [comment]
I would like to contribute too :)

**Comment by KeerthanaHK** [comment]
Hi, @tewarig Can I work on this? I've good collection of notes

**Comment by tewarig** [comment]
yes sure

**Comment by hnishal** [comment]
@KeerthanaHK @Riya-code @pooja-gera you guys know the basics of git, right?

**Comment by Riya-code** [comment]
yes

**Comment by hnishal** [comment]
go ahead fork, add notes and make a pull request

**Comment by pooja-gera** [comment]
Yeah, thank you for asking!

**Comment by ThejasreeKilari** [comment]
Hi I would like to contribute. I've added 2 new folders - Aptitude and C . I've added my notes to it.

**Comment by kalpanaT-05** [comment]
hey @tewarig I've made a new issue on which I'd like to work on so if you find me useful don't forget to assign me that issue

**Comment by tewarig** [comment]
done

**Comment by kalpanaT-05** [comment]
@tewarig hey check your notification i've made changes and made a PR check and merge it and do assign me this issue
thank you in advance
